spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: non_null
    #property-naming-strategy: SNAKE_CASE
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
      USE_BIG_DECIMAL_FOR_FLOATS: true